---
title: "STAT 479 Project Milestone 2"
author: "Dayne Lassiter"
date: "3/11/2022"
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set() 
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(lubridate)
interest <- read_csv('https://github.com/andrewdtu/stat479group3/blob/main/stock.csv?raw=true')
```


```{r}
fullticker = interest$ticker
fullticker[interest$ticker == "GDX"] <- "VanEck Gold Miners (GDX)"
fullticker[interest$ticker == "IYR"] <- "iShares US Real Estate (IYR)"
fullticker[interest$ticker == "XLB"] <- "Materials SPDR (XLB)"
fullticker[interest$ticker == "XLE"] <- "Energy SPDR (XLE)"
fullticker[interest$ticker == "XLF"] <- "Financial SPDR (XLF)"
fullticker[interest$ticker == "XLI"] <- "Industrial SPDR (XLI)"
fullticker[interest$ticker == "XLK"] <- "Technology SPDR (XLK)"
fullticker[interest$ticker == "XLP"] <- "Consumer Staples SPDR (XLP)"
fullticker[interest$ticker == "XLU"] <- "Utilities SPDR (XLU)"
fullticker[interest$ticker == "XLV"] <- "Health Care SPDR (XLV)"
fullticker[interest$ticker == "XLY"] <- "Consumer Discretionary SPDR (XLY)"
fullticker[interest$ticker == "XME"] <- "Metals & Mining SPDR (XME)"
fullticker[interest$ticker == "XOP"] <- "Oil & Gas Explor & Product SPDR (XOP)"
```


```{r wrangle}
interest <- read_csv('https://github.com/andrewdtu/stat479group3/raw/main/stock.csv')%>%
  mutate(Date = as_datetime(Date)) %>%
    mutate(fticker = fullticker)
interest$EFFR[which(interest$EFFR == ".")] <- NA 
interest_2 <-interest%>%
  drop_na()%>%
  mutate(perc_change = ((Close-Open)/Open)*100)%>%
  mutate(EFFR = as.numeric(EFFR))%>%
  group_by(ticker)%>%
  ungroup()
```

```{r close, fig.height = 18, fig.width = 8}
ggplot(interest_2, aes(x=Date,y=Close,color = as.numeric(EFFR)))+
    geom_line(aes(),size = 1)+
    facet_grid(ticker~.,scales = 'free_y')+
    scale_color_viridis_c(option = 'inferno') + 
    labs(title = "Effective Federal Fund Rates for Each ETF Over Time", x = "Year", y = "Closing Price",color = "EFFR")
```

```{r effr, fig.height = 5, fig.width = 8}
ggplot(interest_2,aes(x=Date,y=EFFR))+
  geom_line(Size = 2)+
  labs(title = "EFFR Rates for 2nd Interest Period", x = "Year", y = "EFFR (%)")
```

```{r 2 periods, fig.height = 4, fig.width = 8}
period_1_start = as_datetime('2005-01-12')
period_1_end = as_datetime('2007-06-15')
period_2_start = as_datetime('2017-01-03')
period_2_end = as_datetime('2020-02-03')
interest_periods <- interest_2%>%
  filter(!ticker %in% c('XOP','XME','GDX'))%>%
  select(ticker,Date,Close,fticker)%>%
  filter(Date %in% c(period_1_start,period_1_end,period_2_start,period_2_end))%>%
  pivot_wider(names_from = Date, values_from = Close)%>%
  mutate(period_1_return = (`2007-06-15`-`2005-01-12`)/`2005-01-12`)%>%
  mutate(period_2_return = (`2020-02-03`-`2017-01-03`)/`2017-01-03`)
ggplot(interest_periods, aes(period_1_return,period_2_return,color = fticker))+
  labs(title = "The Return Rate For Each ETF in Period 1 VS Period 2", x = "Period 1 Return Rate (%)", y = "Period 2 Return Rate (%)", color = "Ticker")+
  geom_point(size = 8)+
  scale_color_tableau()
  
```











